version: "3.9"
services:
  pwrstat:
    build: .
    restart: unless-stopped
    ports:
      - "5003:8000"
    devices:
      # - /dev/bus/usb/001/023:/dev/usb/hiddev0
      - /dev/usb/hiddev0:/dev/usb/hiddev0